[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "ISC",
    "BSD-3-Clause",

    "OpenSSL",

    "GPL-3.0",
]
confidence-threshold = 0.66
